server:
  error:
    include-stacktrace: on-param
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true&SSL=false&useTimezone=true&serverTimezone=UTC   
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
